### ISSUE TITLE
[5.3.5] Redirection on logout to internal SSO page

### ISSUE THREAD

**Issue by kevinlacotaco** [dotCMS/core-web#1395]
We are trying to redirect to our internal SSO login portal after logout but due to the logout request being an XHR - it seems to automatically handle that and go to `public/login`. 

Is there anyway we can have a server filter handle this request and redirect to either the index page/or our login portal? 

Found this snippet during logout: 
https://github.com/dotCMS/core-web/blob/869009d1df14a2ae56d4501afd935a542b8678c6/projects/dotcms-js/src/lib/core/login.service.ts#L252-L276

**Comment by jdotcms** [comment]
Hi Kevin

I think you have to choices

1) on the override properties set:

```
logout.service.endpoint.url=my url
```

As soon as the IDP gets back after the logout you should be redirect to it.

2) could try change on the SP metadata the logout location such as 

```
 <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" Location="https://xxx/dotsaml/logout/a14756ea-c5bc-4f1f-bb40-4bd57778cdc1"/>
```

Replace the location by your url
