### ISSUE TITLE
Only admin@dotcms.com can be added as user when permissioned individually

### ISSUE THREAD

**Issue by JohannesDienst** [dotCMS/core-web#1566]
dotCMS version: 5.3.8

When we permission a Content Type individually we cannot add another user to the list with the **Add User** button. This is what our log shows: 
![image](https://user-images.githubusercontent.com/5010638/105819219-3273c080-5fb8-11eb-806c-55cb9c1376d6.png)

We did some digging and found out, that the Admin User does not have a user id like other users. Normally the user id looks something like that: (user-)12345-12335-12345-12345

When we analysed the request that gets send to the backend we noticed that everything after the first **-** gets cut from the param. See Screenshot of web developer console:

![image](https://user-images.githubusercontent.com/5010638/105819604-ad3cdb80-5fb8-11eb-9989-1d219d012bc8.png)

**Comment by wezell** [comment]
Closing as I believe this is already addressed here: dotcms/core#18208
