### ISSUE TITLE
npm run dev error TS2304

### ISSUE THREAD

**Issue by zhartole** [dotCMS/core-web#219]
When I run `npm run dev` I have a lot of errors like this ```src/api/rule-engine/Rule.it-spec.ts(67,11): error TS2304: Cannot find name 'expect'.```
Also in devtools console have error that ```Failed to load resource: the server responded with a status of 404 (Not Found) - http://localhost:9000/build/thirdparty/lodash/lodash.js    ```

**Comment by jtesser** [comment]
we are doing some transition to core-web and moving towards the nom package dotcms-js 

Can I ask though who you are with?  Are you a dotCMS client?

**Comment by zhartole** [comment]
No, Im not a dotCMS client.
Would you provide me a link to issue so I can monitor transition/moving status ?

**Comment by dotcmsCodeReview** [comment]
Its more that we have this
https://github.com/dotCMS/dotJS
https://www.npmjs.com/package/dotcms-js
http://dotcms.com/dotcms-js/#/

There are some issues here
https://github.com/dotCMS/core/issues/9868
https://github.com/dotCMS/core/issues/10024

Can I ask what you are trying to do?  What are you after? Just wondering if
I could help

**Comment by zhartole** [comment]
Thnx for links!

We want to build SPA with Angular2 and use DotCMS as a content management system (also we wanna create some modules on java with SpringMVC). For now we search the best way to get it live. It looks that creating SPA separately and take data by api - the best way. We'll try use dotJS for it.
