### ISSUE TITLE
Add a Copy action when a Workflow Actionlet is "De-linked"

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core-web#573]
Pursuant to the https://github.com/dotCMS/core-web/issues/572 Enhancement we should add the ability to "de-link" an actionlet so that it has it's own id.

Clicking on the link icon could merely de-link or create a copy of the actionlet, possibly with "name - copy", "name - copy1", "name - copy2", behavior for multiple copies with the same name, and this copy action triggered by the click of the link icon would then generate a new actionlet id version with the same properties.  The resultant "copied" actionlet would then no longer be linked to the other actionlets that it had previously been linked to that previously shared the same ID.

**Comment by fmontes** [comment]
Papeleo |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
Patente y permisos de Salud | Maritza | 9/1/2017 |   |   | $0.00 |   |  
Listado de precios | Patricia | 9/2/2017 |   |   |   | P | Documento exportado, hay que comenzar a editarlo
